# Gradle Properties
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true

# Mod Properties
mod.id=simpleplayerlist
mod.version=2.0.0
mod.group=fliplus
mod.name=Simple Player List
mod.description=Introduces the ability to customize server's player list
mod.author=fliplus
mod.license=LGPL-3.0

# Global Dependencies
deps.fabric-loader=0.18.1
deps.devauth=1.2.1